trigger:
  batch: true
  branches:
    include:
      - main
      - release/*

resources:
  repositories:
    - repository: niveristand-custom-device-build-tools
      type:       github
      ref:        main
      endpoint:   nivs-custom-devices
      name:       ni/niveristand-custom-device-build-tools

stages:
  - template: azure-templates/stages.yml@niveristand-custom-device-build-tools
    parameters:
      lvVersionsToBuild:
        - version: '2023'
          bitness: '64bit'
        - version: '2024'
          bitness: '64bit'
        - version: '2025'
          bitness: '64bit'

      buildSteps:
        - projectLocation: 'Source\Custom Device Support\Communication Bus Template Support.lvproj'
          buildOperation: 'ExecuteBuildSpec'
          target: 'My Computer'
          buildSpec: 'Scripting API'

        - projectLocation: 'Source\Custom Device Support\Communication Bus Template Support.lvproj'
          buildOperation: 'ExecuteBuildSpec'
          target: 'My Computer'
          buildSpec: 'System Explorer'

        - projectLocation: 'Source\Custom Device Support\Communication Bus Template Support.lvproj'
          buildOperation: 'ExecuteBuildSpec'
          target: 'My Computer'
          buildSpec: 'Engine'

        - projectLocation: 'Source\Custom Device\Communication Bus Template Custom Device.lvproj'
          buildOperation: 'ExecuteBuildSpec'
          target: 'My Computer'
          buildSpec: 'Configuration Release'

        - projectLocation: 'Source\Custom Device\Communication Bus Template Custom Device.lvproj'
          buildOperation: 'ExecuteBuildSpec'
          target: 'My Computer'
          buildSpec: 'Engine Release'

        - projectLocation: 'Source\Custom Device Support\Communication Bus Template Support.lvproj'
          buildOperation: 'ExecuteBuildSpec'
          target: 'Linux x64'
          buildSpec: 'Engine'

        - projectLocation: 'Source\Custom Device\Communication Bus Template Custom Device.lvproj'
          buildOperation: 'ExecuteBuildSpec'
          target: 'Linux x64'
          buildSpec: 'Engine Release'

      releaseVersion: '25.0.0'
      buildOutputLocation: 'Source\Built'
      archiveLocation: '\\nirvana\Measurements\VeriStandAddons\communication_bus_template'

      packages:
        - controlFileName: 'control_custom_device'
          payloadMaps:
            - installLocation: 'documents\National Instruments\NI VeriStand $(lvVersion)\Custom Devices\Communication Bus Template'
              payloadLocation: ''

        - controlFileName: 'control_scripting'
          payloadMaps:
            - installLocation: 'ni-paths-LV$(lvVersion)DIR\vi.lib\addons\VeriStand Custom Device Scripting APIs\Communication Bus Template'
              payloadLocation: 'Scripting'
