[archive]
build_output_dir = 'Source\Built'
archive_location = '\\nirvana\Measurements\VeriStandAddons\communication_bus_template'

[projects.support]
path = 'Source\Custom Device Support\Communication Bus Template Support.lvproj'

[projects.cd]
path = 'Source\Custom Device\Communication Bus Template Custom Device.lvproj'

[[build.steps]]
name = 'Scripting API'
type = 'lvBuildSpec'
project = '{support}'
target = 'My Computer'
build_spec = 'Scripting API'

[[build.steps]]
name = 'System Explorer PPL'
type = 'lvBuildSpec'
project = '{support}'
target = 'My Computer'
build_spec = 'Communication Bus System Explorer'

[[build.steps]]
name = 'Engine PPL'
type = 'lvBuildSpec'
project = '{support}'
target = 'My Computer'
build_spec = 'Communication Bus Engine'

[[build.steps]]
name = 'Configuration Library'
type = 'lvBuildSpec'
project = '{cd}'
target = 'My Computer'
build_spec = 'Configuration Release'

[[build.steps]]
name = 'Engine Library'
type = 'lvBuildSpec'
project = '{cd}'
target = 'My Computer'
build_spec = 'Engine Release'

[[build.steps]]
name = 'Linux x64 Engine PPL'
type = 'lvBuildSpec'
project = '{support}'
target = 'RT CompactRIO Target - Linux x64'
build_spec = 'Communication Bus Engine'

[[build.steps]]
name = 'Linux x64 Engine Library'
type = 'lvBuildSpec'
project = '{cd}'
target = 'RT CompactRIO Target - Linux x64'
build_spec = 'Engine Release'

[[package]]
type = 'nipkg'
payload_dir = 'Built'
install_destination = 'documents\National Instruments\NI VeriStand {veristand_version}\Custom Devices\Communication Bus Template'
control_file = 'control_custom_device'
package_output_dir = 'Source\Built'

[[package]]
type = 'nipkg'
payload_dir = 'Source\Built\Scripting'
install_destination = 'ni-paths-LV{veristand_version}DIR\vi.lib\addons\VeriStand Custom Device Scripting APIs\Communication Bus Template'
control_file = 'control_scripting'
package_output_dir = 'Source\Built'
