[archive]
build_output_dir = 'Source\Built'
archive_location = '\\nirvana\Measurements\VeriStandAddons\communication_bus_template'

[dependencies.local]
libraries = ['Source\Built\Interfaces\Communication Bus Interfaces.lvlibp']
copy_location = 'Includes'

[projects.interfaces]
path = 'Source\Interfaces\Communication Bus Template Interfaces.lvproj'

[projects.cd]
path = 'Source\Custom Device\Communication Bus Template Custom Device.lvproj'

[[build.steps]]
name = 'Bus Interfaces'
type = 'lvBuildSpec'
project = '{interfaces}'
target = 'My Computer'
build_spec = 'Communication Bus Interfaces'

[[build.steps]]
name = 'Configuration Library'
type = 'lvBuildSpec'
project = '{cd}'
target = 'My Computer'
build_spec = 'Configuration Release'
dependency_target = '_' # Needed to opt in to the dependency copying, even though the path is currently OS-agnostic

[[build.steps]]
name = 'Engine Library'
type = 'lvBuildSpec'
project = '{cd}'
target = 'My Computer'
build_spec = 'Engine Release'
dependency_target = '_' # Needed to opt in to the dependency copying, even though the path is currently OS-agnostic

[[build.steps]]
name = 'Scripting API'
type = 'lvBuildSpec'
project = '{cd}'
target = 'My Computer'
build_spec = 'Scripting API'
dependency_target = '_' # Needed to opt in to the dependency copying, even though the path is currently OS-agnostic

[[package]]
type = 'nipkg'
payload_dir = 'Built'
install_destination = 'documents\National Instruments\NI VeriStand {veristand_version}\Custom Devices\Communication Bus Template'
control_file = 'control_custom_device'
package_output_dir = 'Source\Built'

[[package]]
type = 'nipkg'
payload_dir = 'Source\Built\Scripting'
install_destination = 'ni-paths-LV{veristand_version}DIR\vi.lib\addons\VeriStand Custom Device Scripting APIs\Communication Bus Template'
control_file = 'control_scripting'
package_output_dir = 'Source\Built'
