[archive]
build_output_dir = 'Source\Built'
archive_location = '\\nirvana\Measurements\VeriStandAddons\communication_bus_template'

[projects.interfaces]
path = 'Source\Interfaces\Communication Bus Template Interfaces.lvproj'

[projects.cd]
path = 'Source\Custom Device\Communication Bus Template Custom Device.lvproj'

[[build.steps]]
name = 'Bus Interfaces'
type = 'lvBuildSpec'
project = '{interfaces}'
target = 'My Computer'
build_spec = 'Communication Bus Interfaces'

[[build.steps]]
name = 'Configuration Library'
type = 'lvBuildSpec'
project = '{cd}'
target = 'My Computer'
build_spec = 'Configuration Release'

[[build.steps]]
name = 'Engine Libraries'
type = 'lvBuildSpecAllTargets'
project = '{cd}'
build_spec = 'Engine Release'

[package]
type = 'nipkg'
payload_dir = 'Built'
install_destination = 'documents\National Instruments\NI VeriStand {veristand_version}\Custom Devices\Communication Bus Template'
